### PR TITLE
Move to GitHub Actions CI

### PR DESCRIPTION
**Pull request by pmatos**
Drops Travis to consolidate CI in GHA. Removes broken archs - future PR will add these archs once we fix them.

### CODE REVIEW

**Comment by pmatos** [comment]
Unfortunately I don't have permissions here to set reviewers, labels or assignees. Happy for someone to assign this to me. Maybe @mflatt or @samth ?

**Comment by samth** [comment]
That should be fixed now.

**Comment by samth** [comment]
This is good to merge, although we might drop the `travis:fold` lines.

**Comment by pmatos** [comment]
> That should be fixed now.

Thanks

**Comment by pmatos** [comment]
> This is good to merge, although we might drop the `travis:fold` lines.

`travis:fold`? Can't find any reference travis in my diff. Maybe I misunderstood?

**Comment by samth** [comment]
It's not in the diff, but it is in the unchanged parts of the shell scripts.

**Comment by pmatos** [comment]
> It's not in the diff, but it is in the unchanged parts of the shell scripts.

I will take a look.

**Pull request merged**
