### PR TITLE
Add reboot pathway to CI

### PR DESCRIPTION
**Pull request by jryans**
As [discussed a while ago](https://github.com/racket/racket/issues/4601#issuecomment-1462903695), it would be good to have CI coverage of the reboot pathway.

This adds a Linux variant to CI which covers this additional bootstrapping dimension.

### CODE REVIEW

**Comment by samth** [comment]
This looks good to me. @mflatt, what do you think?

**Comment by mflatt** [comment]
Yes, this looks like a good idea to me. I think it will be best to handle it at cisco/ChezScheme after the impending merge, though.

**Comment by jryans** [comment]
> I think it will be best to handle it at cisco/ChezScheme after the impending merge, though.

Ah okay, seems reasonable to me. I can resubmit the PR over there after the merge then.

Is there an issue / PR / discussion I can follow about this upcoming merge? I can't seem to find anything about it after a few searches...

**Comment by mflatt** [comment]
> Is there an issue / PR / discussion I can follow about this upcoming merge?

I'm working on a post to the chez-scheme group at groups.google.com, so it will be there soon.

**Comment by jryans** [comment]
I have recreated this PR upstream: https://github.com/cisco/ChezScheme/pull/730

**Pull request closed without merging**
