### PR TITLE
Use setenv rather than putenv on non WIN32 environments

### PR DESCRIPTION
**Pull request by alshopov**
Signed-off-by: Alexander Shopov <ash@kambanaria.org>

### CODE REVIEW

**Comment by alshopov** [comment]
See https://github.com/cisco/ChezScheme/pull/445

**Comment by alshopov** [comment]
I am closing this as the upstream cisco#445 has been merged. This change should precipitate during a future merge.

**Comment by mflatt** [comment]
Just to confirm, I've pulled the upstram commits, so this is now merged. Thanks!

**Comment by alshopov** [comment]
> I've pulled ...
Thank you, that was indeed fast.

**Pull request closed without merging**
