### PR TITLE
Remove variable dead store from glzdopen

### PR DESCRIPTION
**Pull request by pmatos**

### CODE REVIEW

**Comment by mflatt** [comment]
I think this is probably fixed in the main Chez branch, so I should try syncing with that. Stay tuned, and then we'll check again.

**Comment by mflatt** [comment]
I think this code really was replaced. Ok to close?

**Comment by pmatos** [comment]
@mflatt are we getting this merged in racket/ChezScheme? At this point, racket/ChezScheme is really what I care about. If we are slowly diverging with mainline Chez, I am honestly not interested in this point in fixing stuff for Chez only. I am trying to get Racket as clean as possible. 

Can we leave this open until it is merged in? It would help me understand from all the complaints the static analyzer is throwing, which ones I have looked at already.

**Comment by mflatt** [comment]
Yes, it is merged already... I see that I forgot to also update `mflatt/ChezScheme`, too, but I doubt that's the issue, so maybe I'm confused about something else. Does "compress-io.c" in this repo still have the problem?

**Comment by pmatos** [comment]
I wonder if the CI is still using the old `mflatt/ChezScheme` or if it's for some reason not updating automatically... I will check and fix this on the CI side. Lets close this then. Thanks!

**Pull request closed without merging**
