### PR TITLE
Racket/docs copyediting

### PR DESCRIPTION
**Pull request by jltaylor-us**

### CODE REVIEW

**Comment by mflatt** [comment]
Thanks!

Do you have an opinion on merges and Git history? I would normally squash a set of changes like this to a single commit, because I find that more useful when looking at Git history. But keeping the history and merge commits is also ok with me.

**Comment by jltaylor-us** [comment]
In this specific case, I don't think there's anything to be gained by keeping the commit history.  In other circumstances (when editing code instead of docs), I'll generally try to make each commit a logical self-contained, coherent unit (in which case the commit history _might_ be useful).  My general observations from other projects are that unless everyone is committed (no pun intended) to making their branch histories "useful" that keeping those histories is pointless.  (In other words, squashing is probably a good default... although it occurs to me that part of the reason for that is that I don't think the GitHub UI has any option that's the equivalent of using the `--first-parent` flag to `git log`.)

You might also want to wait a bit to see if the other Chez maintainers have any feedback on the PR, since I pinged everyone via email.  (Although I don't think there's anything stopping them from adding comments after it's already merged?)

**Comment by mflatt** [comment]
Got it. Also, I see that I created conflicts recently by editing the documentation. So, I could add a proposed resolution of the conflicts here, but I'll wait a little while.

**Comment by jltaylor-us** [comment]
I thought I pulled and resolved conflicts... are the conflicts left?  (GitHub says there are no conflicts with the base branch)

**Comment by mflatt** [comment]
Ah, looks like I'm confused. I'll try again (just locally).

**Comment by mflatt** [comment]
Merged as a899acf65cdf4205f9265cb1e84e6c892bc78c73.

**Pull request closed without merging**
