### PR TITLE
Try to eliminate dead stores

### PR DESCRIPTION
**Pull request by alshopov**
Sometimes this allows removal of conditional or docs

Signed-off-by: Alexander Shopov <ash@kambanaria.org>

### CODE REVIEW

**Comment by alshopov** [comment]
See https://github.com/cisco/ChezScheme/pull/444

**Comment by alshopov** [comment]
There is a problem with the build due to some [unexpected reason](https://travis-ci.com/racket/ChezScheme/jobs/215313417): 
```

installer.sh: 2: installer.sh: Syntax error: newline unexpected
~/racket/bin/racket -v
.travis/dobootfile.sh: line 13: /home/travis/racket/bin/racket: No such file or directory
~/racket/bin/raco pkg install -i --auto --no-setup cs-bootstrap
.travis/dobootfile.sh: line 14: /home/travis/racket/bin/raco: No such file or directory
~/racket/bin/raco setup -D cs-bootstrap
.travis/dobootfile.sh: line 15: /home/travis/racket/bin/raco: No such file or directory
cd ChezScheme/
export MACH=$TARGET_MACHINE
~/racket/bin/racket -l cs-bootstrap
.travis/dobootfile.sh: line 20: /home/travis/racket/bin/racket: No such file or directory
The command ".travis/dobootfile.sh" failed and exited with 127 during .
Your build has been stopped.
```

**Comment by samth** [comment]
That error is because the latest Racket snapshot build failed, so none of the Travis runs are going to work.

**Comment by alshopov** [comment]
> That error is because the latest Racket snapshot build failed, so none of the Travis runs are going to work.

What should I do then @samth?

**Comment by samth** [comment]
There's nothing you can do currently.

**Comment by samth** [comment]
I've now restarted the CI.

**Comment by alshopov** [comment]
Closing as this has been merged upstream - https://github.com/cisco/ChezScheme/pull/444. After some future merge it will come here as well.

**Pull request closed without merging**
