### PR TITLE
Initial test of arm64 runner

### PR DESCRIPTION
**Pull request by pmatos**
Work in progress...

### CODE REVIEW

**Comment by pmatos** [comment]
Tests are still running but the infrastructure seems to be in place.
Building cgc takes almost 50mins - which is ridiculous. But until we build a snapshot on the racket side can't think of a better alternative.

**Comment by pmatos** [comment]
@mflatt can you look at `test.sh` and see if it's testing everything we want to test?

**Comment by pmatos** [comment]
@mflatt https://github.com/racket/ChezScheme/blob/master/.github/scripts/test.sh

**Comment by mflatt** [comment]
That's a fine set of tests. If the cost of adding more is low enough, I'd throw in `runmats o=0 cp0=t`.

**Comment by pmatos** [comment]
@mflatt would you have expected this to happen?

**Comment by mflatt** [comment]
@pmatos I'm not sure what you mean. Expected what to happen?

**Comment by pmatos** [comment]
> @pmatos I'm not sure what you mean. Expected what to happen?

Stupid question without reference - sorry. This: https://github.com/racket/ChezScheme/runs/864714491?check_suite_focus=true#step:8:160

**Comment by mflatt** [comment]
No, there are no expected failures. I don't immediately know whether it's a problem with the test, such as making too many assumptions about file permissions.

**Comment by pmatos** [comment]
> No, there are no expected failures. I don't immediately know whether it's a problem with the test, such as making too many assumptions about file permissions.

OK - I won't merge until I investigate.

**Comment by pmatos** [comment]
> No, there are no expected failures. I don't immediately know whether it's a problem with the test, such as making too many assumptions about file permissions.

Interesting, I can repro the issue when running inside the container even though you are root, so you should definitely now have permission problems.

**Comment by pmatos** [comment]
Why does the testfile `unix.ms` start with: `(if (or (windows?) (equal? (getenv "USER") "root") (embedded?))`
We run as `root` in the container but we don't hit this because `USER` is unset. I don't understand the point of `(equal? (getenv "USER") "root")`.

In any case I will investigate.

**Comment by samth** [comment]
My guess is that some of those tests were thought to be unreliable when running as root, perhaps because they didn't fail in the correct way. It may also be that most other situations where the user is root, `USER` is set appropriately (it is when I use either `su` or `sudo` on my machine).

**Comment by pmatos** [comment]
> My guess is that some of those tests were thought to be unreliable when running as root, perhaps because they didn't fail in the correct way. It may also be that most other situations where the user is root, `USER` is set appropriately (it is when I use either `su` or `sudo` on my machine).

Unfortunately the docker container doesn't set `USER`. I have read that one of the docker best practices is to run your process user a non-root user so I might consider that for our CI workflows. I will run a couple more tests.

**Pull request merged**
